### ISSUE TITLE
gamemode permission bug

### ISSUE THREAD

**Issue by Creeperface01** [LegendOfMCPE/EssentialsPE#149]
i m OP and i cant use command /gamemode it say i have not permissions

**Comment by Lucario2** [comment]
see

**Comment by Lucario2** [comment]
SEE!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by 64FF00** [comment]
@Lucario2 https://github.com/LegendOfMCPE/EssentialsPE/wiki/Permission-Nodes

**Comment by Creeperface01** [comment]
So i must give permission to console to allow change gamemode from console :D

**Comment by 64FF00** [comment]
@Creeperface01 Yup! :3

**Comment by Lucario2** [comment]
I'm op to and I can't /gamemode. I can only do /gmc or /gma But I can't give other people Gamemode like that. I added the permission node. still doesnt work. I'M OP. This is getting annoying to me I am not trying to get banned on github. Im just trying to let you know that something is off with this plugin... A similar issue happened to my vote reward, it said it couldn't get vote information and my api key was correct. It wasnt working. Then a few days later it fixed itself. I'm like WTF!?!? IT WORKS!!!!!!! But how?? This was really weird for me. Because it ACTUALLY fixed itself. Maybe the same will happen to essentials pe? I highly doubt that. All im saying is that I'm op and I can't do /gamemode

**Comment by Lucario2** [comment]
Wasn't /gamemode originally from the pocketmine source?

**Comment by Georggi** [comment]
Just curious to see if that actaully fixed it @Lucario2 @Creeperface01 can you check that?

**Comment by ZizzyZizzy** [comment]
Just so you know, this fix did NOT make it into the 1.1.2 build on the Pocketmine.net plugins page. I've downloaded the fixed v1.1.2 from here:
https://github.com/LegendOfMCPE/EssentialsPE/tree/89044a9c05fcec4e8a849b4fc3748a46a4c783c6

...and that version DOES have the fix for this issue, even though it says it's the exact same version.

You can make a .phar file from the .zip using this page:
http://pmt.mcpe.me/
(Default options work fine.)

**Comment by WOWR** [comment]
Please help me fix gamemode bug. Its says not permission for console and players. Even when I do set permissions it doesn't work! Please help!

**Comment by Falkirks** [comment]
@WOWR What version are you using?
