### ISSUE TITLE
Can you add /thor command? or lighting its thor? And fix command /kick all

### ISSUE THREAD

**Issue by SoyPro** [LegendOfMCPE/EssentialsPE#176]
You add lighting,its the same /thor? And fix /kick all its not working property because when players are kicked,it kill them

**Comment by iksaku** [comment]
2 things:
 1. Check the code to see which "aliases" are available for each command before asking.
 2. Don't spam your own problems, it's pretty known that since MCPE 0.12 some things like "server kicking" sometimes doesn't work, so please just "HARD TEST" before spamming the same thing in nested issues and closed ones
