### ISSUE TITLE
Timeout after adding plugin

### ISSUE THREAD

**Issue by astrophylite** [LegendOfMCPE/EssentialsPE#273]
When I install PocketMine-MP on my Ubuntu 14.04 server, I can join it perfectly fine.
When I stop the server to add EssentialsPE and start it back up again, it loads but then it keeps timing my MC:PE client out.

Yes, I do have to use the development version because I want to use MC:PE 0.15.0.

Any help will be appreciated,
Astrophylite.

**Comment by samalero** [comment]
the same ... + developer does not believe me!

**Comment by samalero** [comment]
anyone help?

**Comment by xFyreWolfx** [comment]
Came across this issue when troubleshooting a similar connection problem. Disabling the plugin solves the issue. Apparently, PocketMine 0.15.0+ and EssentialsPE v2.0.0 conflict with each other and don't allow connections through.

I hate to post another one of those "me too!" comments, but I'm without a solution at the moment.

**Comment by samalero** [comment]
I have created a request for correction, but they were ignored. Therefore, I wrote a problem and I have ...

**Comment by ZizzyZizzy** [comment]
The Genisys 0.15 build works fine with EssentialsPE, but ClearSky php7 0.15 is disconnecting players when they try to join.

Debug level 3 is no help:
22.06 20:02:22 [Server] Server thread/INFO XXXXXX [/192.168.0.117:19132] logged out due to timeout
22.06 20:02:22 [Server] Server thread/INFO XXXXXX left the game
22.06 20:02:13 [Server] Server thread/INFO XXXXXX joined the game
22.06 20:02:12 [Connect] User VirtualGladiatr, IP 192.168.0.117
22.06 20:02:12 [Server] Server thread/DEBUG Setting up final values...
22.06 20:02:12 [Server] Server thread/DEBUG Setting up new values...
22.06 20:02:12 [Server] Server thread/DEBUG Creating virtual session...
22.06 20:02:12 [Server] Server thread/INFO Running
22.06 20:02:12 [Server] Server thread/DEBUG Creating player session file...

**Comment by Aericio** [comment]
Yeah, EssentialsPE doesn't seem to work  with ClearSky :(

**Comment by Sandertv** [comment]
Sorry for EssentialsPE not supporting ClearSky. I do not know what the problem is.

**Comment by Aericio** [comment]
Oh, EssentialsPE works for ClearSky now.

**Comment by Sandertv** [comment]
It does? Well that's awesome!
