### ISSUE TITLE
EssentialsPE + ClearSky php7 = timeout login error.

### ISSUE THREAD

**Issue by andris155** [LegendOfMCPE/EssentialsPE#278]
https://github.com/ClearSkyTeam/ClearSky/issues/584

**Comment by flaxues** [comment]
Port of Bukkit Essentials for *@PocketMine* Servers

ClearSky is not supported.

**Comment by flaxues** [comment]
Oh and if you had readed the readme.md it says:

The port version of Bukkit Essentials for PocketMine-MP Software.

EssentialsPE does *not* officially provide compatibility with Modded PocketMine-MP server software

Nevertheless compatibility can be found sometimes, but do not complain if it does not appear.

**Comment by snooblife** [comment]
This issue has been reported before with timeout errors and it occurs on PocketMine-MP as well.

Also even if the fact that the plugin does not officially support modified PocketMine-MP, it is clear that many thousands of others do and use this plugin and other plugin which were made for pocketmine. 
The user agreements show that the code can be modified by others so it is good to ask for help when using plugins that dont work so others can help and maybe post working versions.
Im sure the authors would like to keep their own plugins in order rather than having various plugins(the same) for different versions for different MCPE server builds by third parties like pocketmine-mp does, hence not further fragmenting their work.
