### ISSUE TITLE
[URGENT] Not sure what is happening: Undefined Offset 275 on line 512 and line 514

### ISSUE THREAD

**Issue by MajorPlayz** [LegendOfMCPE/EssentialsPE#286]
[Server] 
[Server] Notice: Undefined offset: 275 in phar:///storage/emulated/0/PocketMine/plugins/Essentials.phar/src/EssentialsPE/BaseFiles/BaseSession.php on line 512
[Server] 
[Server] Notice: Undefined offset: 275 in phar:///storage/emulated/0/PocketMine/plugins/Essentials.phar/src/EssentialsPE/BaseFiles/BaseSession.php on line 514

I have latest version of Essentials

**Comment by Adam1609** [comment]
Do you have World Edit?

**Comment by MajorPlayz** [comment]
@Adam1609 yes, I have MagicWE by @Thebigsmilexd 

Any ideas?

**Comment by thebigsmileXD** [comment]
:P

**Comment by MajorPlayz** [comment]
@thebigsmileXD ik xD also ur we is the best we I have ever used thanks so much for making it 👍 xD

**Comment by MajorPlayz** [comment]
Does anybody else have any ideas? @onebone @Legendofmcpe

**Comment by thebigsmileXD** [comment]
(off toppic) Did you already update so you have cylinders?

**Comment by MajorPlayz** [comment]
Yes I have

**Comment by MajorPlayz** [comment]
I found your plugin yester-morning :D

**Comment by MajorPlayz** [comment]
Just to say, I am using genisys 0.15.X and is php7 api 2.0.0

That might help

**Comment by SOF3** [comment]
Please don't advertise other plugins here. As long as you have confirmed this issue is not related to World Edit, I believe any more discussion is irrelevant, especially about its recent updates. Talking about cylinders is totally advertising.

**Comment by thebigsmileXD** [comment]
Advertising would be: DOWNLOAD MY AWESOME MCPE POCKETMINE PLUGIN ITS SO COOL SO HELPFUL MUST HAVE YOU NEED IT NOOOOOOOOW!!!! MAGICWE!!! I CODED THIS CHECK IT OUT U WANT THIS BELIEVE ME. Didn't do this though. Also i had no idea why he even mentioned my plugin .-.

**Comment by thebigsmileXD** [comment]
And also you did it again. Saying that someone advertises. So because you don't seem to know what advertising means: http://www.dictionary.com/browse/advertising

**Comment by SOF3** [comment]
@thebigsmileXD according to [Cambridge dictionary](http://dictionary.cambridge.org/dictionary/english/advertise):

> to make something known generally or in public, especially in order to sell it

As the Internet culture continues to develop nowadays, advertisement is no longer limited to selling (we don't need to argue on this, do we?). However, advertising is inevitably the action to make something more well-known generally. This definition, however, depends on reader's common sense. For example, if the department for hygiene from your government keeps putting television commercials to prevent the Zika virus, and tells you to do all kinds of measures to prevent mosquito growth. These commercials are advertisements doubtlessly, but they are not advertising mosquitoes or advertising the Zika virus. Instead, the subject of the advertisement is the _prevention_ of mosquitoes/Zika virus. This shows that advertisement refers to the action of spreading the news to the public that something is _good_ or _should be done_, regardless of whether or not the public already knows about it.

Mentioning about the cylinder functionality in your plugin obviously doesn't have anything to do with this thread, so what are the possible reasons? Here are a few suggestions:

1. Maybe you care about your users so much. Maybe you aren't a business, so maybe you don't need excellent customer support service, so maybe you are really an altruist, so maybe you are really gonna make a bot and search for servers that use MagicWE and probably join these servers and probably remind their server admins to update the plugin, probably without even causing nuisance to other players. *I will not and cannot disprove this possibility*. If this is probably the case, I probably have to thank you for probably making such a great altruistic selfless contribution where your very tiny little step will probably push the overall development of our race of _Homo sapiens_ a probably unbelievably giant step forwards. Maybe I shouldn't be in your way, because you are probably [saving children's lives by keeping them warm in the winter](https://xkcd.com/1172).
2. Maybe you are just expecting other people reading this issue to be acknowledged that the MagicWE plugin has a cylinder functionality. Maybe this is a way where you let more people know how outstanding it is. Maybe you are advertising about the feature of cylinders, to an unknown potential group of people reading this issue for an unknown potential reason who will potentially become interested and potentially think that your plugin is probably worth downloading and potentially become users of your plugin.
3. Maybe you are trying to make people think/know/believe/suspect/realize you probably have excellent customer support service, even though they are probably not customers, and maybe you are trying to earn reputation for yourself being so friendly to your users. Maybe I should stop deducing this theory since this is so conspiratorial.

**Logical fallacy warning: the above deduction probably involves a slipper slope, but the possibility for this deduction to be correct still stands, and therefore should not be considered as a rumour.**

Well after all I'm not a @LegendOfMCPE member. Maybe this is none of my business. Maybe I should unsubscribe this repo. Maybe I should never have posted this. Maybe I accidentally clicked Ctrl+Enter unintentionally. Maybe I logged out after accidentally posting this comment. Maybe I didn't know I really posted this comment. Maybe I forgot about this issue. Maybe I will never check this issue again. Maybe one day I would come back and read this issue and find out that I am doing floccinaucinihilipilification here talking to nobody, not even members of @LegendOfMCPE who would read this issue. Maybe [I am just dreaming, and I am actually a butterfly dreaming as a human](https://en.wikiquote.org/wiki/Zhuangzi#Zhuangzi).

**Comment by MajorPlayz** [comment]
Guys does anybody know how do fix this... 

Because I kind of need it...

@SOF3 Do you know how to fix this?
@Adam1609 
@thebigsmileXD 
@leedm777 
@LDX-MCPE 
@LegendOfMCPE

**Comment by MajorPlayz** [comment]
Does anybody know

**Comment by thebigsmileXD** [comment]
@SOF3 i thought you didnt wanted to talk about this anymore? You are just a stubborn head.

**Comment by LDX-MCPE** [comment]
@MajorPlayz Someone on the team will look at it soon. Please be patient.

**Comment by SOF3** [comment]
@MajorPlayz Please provide steps to reproduce this. This appears to be something related to PowerTool.

**Comment by MajorPlayz** [comment]
@LDX-MCPE Ok thanks and @SOF3 I just installed the latest version of EssentialsPE and in console it dislays that error. Thanks for everybodys help :D also sorry I havent been able to reply I was on holiday.

**Comment by MajorPlayz** [comment]
@SOF3 Yes, I believe so as /pt gives me an error however the console error apperas regulary even when /pt or /powertool is not used.

**Comment by MajorPlayz** [comment]
Ok thank-you

**Comment by MajorPlayz** [comment]
Off-Topic: Where can I find the code for `essentials.spawn.use`? On-Topic: It isn't `/pt` as i get this error whenever I (or anybody else) places a block or removes a block with their own skill not world edit (@Adam1609 You were sort of right XD)

**Comment by SOF3** [comment]
Since you know it is off-topic, don't say it here!

**Comment by thebigsmileXD** [comment]
![image](https://cloud.githubusercontent.com/assets/8733998/19165300/9035a14e-8c03-11e6-8dd3-068f984ecc1e.png)
@MajorPlayz ever saw that

**Comment by MajorPlayz** [comment]
:P

**Comment by zahf22** [comment]
same problem on me

**Comment by Sandertv** [comment]
I've fixed this in the pull request I made. Try using that version.
