### ISSUE TITLE
PlayerJoinEvent error

### ISSUE THREAD

**Issue by SuperKali** [LegendOfMCPE/EssentialsPE#400]
* PocketMine Version: I use GenisysPro 1.1
* EssentialsPE Version: 2.0.0
* Game Version: PE / Windows 10

[07:06:23] [Server thread/CRITICAL]: InvalidState
Exception: "Trying to get permissions of closed p
layer" (EXCEPTION) in "/src/pocketmine/Player" at
 line 689                                        
[07:06:30] [Server thread/INFO]: [EssentialsPE] R
unning                                           
[07:06:30] [Server thread/CRITICAL]: "Could not p
ass event 'pocketmine\event\player\PlayerJoinEven
t' to 'EssentialsPE v2.0.0': Trying to get permis
sions of closed player on EssentialsPE\EventHandl
ers\PlayerEvents                                 
[07:06:30] [Server thread/CRITICAL]: InvalidState
Exception: "Trying to get permissions of closed Player" (EXCEPTION) in "/src/pocketmine/Player" a
 line 689

**Comment by Sandertv** [comment]
Unless you can confirm this happens on PocketMine too, I can't resolve your issue.

**Comment by MasterOfTheRealm** [comment]
No helping hand for forks? not even as a branch so changes won't affect PMMP?

**Comment by Sandertv** [comment]
Through discussing with the team some time ago we have decided not to provide any support for forks and ignore their existance. I'm not going to waste my (already lacking) time on trying to support forks too.

**Comment by DerddyDert** [comment]
@Sandertv I understand you and appreciate your work. Actually, I'm quite a fan of your work. However, GeniysPro is a direct decendant of Genisys in code as well as developers. Pocketmine, Genisys and Imagicalmine were some of the main legit servers back in the day. Imagicalmine has since died off. And spoons are a dime a dozen. 

My point is Genisyspro team has been cleaning house, getting organized and getting back on track with what Genisys was doing as being a stable alternative to pocketmine with extended features. Nothing more and nothing less. We are working on backward compatibility with PMMP due to devs like yourself. However, more people are using Genisyspro than you may be aware of. I'm talking a lot, and some are very large. I don't know of other spoons that are as legit as PMMP and Genisyspro. Cortex is doing great things with his spoon but that's proprietary.

Your projects are up to you but due to the volume of Genisyspro users you may want to consider offering some limited support. Also, if you and your team would like you could assist us temporarily to line things back up to be backwards compatible with PMMP as far as plugins go. That's simply an invitation and up to you. If none of that intrests you, heck, at least try out our latest src. You may like it.

**Comment by Sandertv** [comment]
@DerddyDert as strict as it may sound, the rest of the team has decided to ignore the existance of forks. (Note, we could have voted to write code to explicitely disallow it from working on forks.) There's nothing I can do about that. I'm not going to write code just so that it doesn't work on GenisysPro, but I'm not going to change things to get it supported either. A very small change at max, but that's it.

Furthermore, this issue is not an issue directly caused by EssentialsPE. You could try the latest commit where this has been moved to PlayerLoginEvent. It seems like the join sequence in GenisysPro isn't entirely correct.

**Comment by DerddyDert** [comment]
Thanks for your response. At least you are not pretentious like a lot of devs are becoming. Especially those trying to block spoons. That means the spoon devs have to disable/bypass the code at the core and/or fork the plugins and pull the anti-open-source-attitude code out. Where there is a demand, there is a market and PMMP just isn't cuttin' it as far as serving everyone with one spoon. (Its great software though) Thanks for the tip! We have been working on the join sequence as the update from 1.0.9 was quite a challenge and your input is useful.

**Comment by dktapps** [comment]
> GeniysPro is a direct decendant of Genisys in code as well as developers.

That's bullshit. Shall I tell you how many Genisys developers work on that spoon? None. I know the Genisys developers (the real ones). I was a Genisys developer myself.

GenisysPro is no different to any other spoon out there. You can try and play it up like you're legit, but you're all full of crap trying to make a name for yourselves.
